name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Configure Enviroment
      run: \"A\" >> Swe2_tour_planer/bin/Debug/net5.0-windows/Appsettings.json
    - name: Test
      run: dotnet test --no-build --verbosity normal
